# This workflows just forces virtual_hardware.yml workflow to run
name: Caller Arm Virtual Hardware
on:
  pull_request:
    paths:
      - .github/workflows/caller_virtual_hardware.yml
      - amazon-freertos/**/*
      - config_files/**/*
      - framework/layer/Board/AVH_MPS3_Corstone-300/IoT/**/*
      - framework/layer/Socket/VSocket/**/*
      - RTE/**/*
      - app_main.c
      - Demo.*.yml
  workflow_dispatch:
jobs:
  upload_pr_number:
    runs-on: ubuntu-latest
    steps:
      - name: Save PR number
        run: |
          mkdir -p ./pr
          echo -n "${{ github.event.number }}" > ./pr/pr_number
      - uses: actions/upload-artifact@v3
        with:
          name: pr_number
          path: pr/
